I have updated devs.txt with my name
nwplus/cms pull request #39
Opened 2020-05-28 01:25 UTC by Ciuffi

This is my first PR at nw

2020-05-28 01:31 UTC, ianmah requested changes

2020-05-28 01:31 UTC, ianmah commented on devs.txt
> +Giulio Rossi - @ciuffi - just an update for the pr
```suggestion
Giulio Rossi - @ciuffi 
```

2020-05-28 01:39 UTC, panjenny0 approved these changes
LGTM!

2020-06-04 01:13 UTC, ianmah approved these changes

2020-07-20 20:39 UTC, merged