Finished Auth
nwplus/cms pull request #8
Opened 2019-08-29 00:48 UTC by AustinKobayashi

Finished auth. Requires an email in the firebase 'admins' database

2019-08-29 02:30 UTC, Ciuffi reviewed
Doesn't seem to be working for me.. I added myself to firebase but I keep getting permission denied when I try to login. Have any idea why?

2019-08-29 02:48 UTC, Ciuffi approved these changes
Okay works now, the UID in the admin collection has to be the same as in firebase authentication

2019-08-29 04:01 UTC, Eric1015 commented on pages/index.vue
> +        console.log(e.code)
Maybe you don't need 'console.log'

2019-08-29 06:51 UTC, Ciuffi requested changes
Sorry just two more things, could you add a logout button and a redirect in index.vue to the CMS if you're already authenticated?

2019-09-08 23:03 UTC, Ciuffi approved these changes
very persistent

2019-09-09 02:36 UTC, merged